### ISSUE TITLE
WalletConnect Integration

### ISSUE THREAD

**Issue by ukstv** [LedgerHQ/ledger-live-mobile#1040]
- [x] I have checked this feature was not yet requested.

Ledger Live Mobile would be a wonderful mobile Ethereum wallet if it would make using Ethereum accounts on the web. One standard that connects mobile Ethereum wallets to desktop web is [WalletConnect](https://walletconnect.org). The request is integration of WalletConnect into Ledger Live Mobile application.

#### Part of the application

The feature would significantly affect user interface of the application.
1. It would have an additional button for scanning WalletConnect QR codes.
2. It would handle approving Ethereum actions on Nano X dongle through mobile UI.

**Comment by reuptaken** [comment]
While WalletConnect is a way to connect desktop dapps to mobile wallets this could also help with dapps opened in browser on mobile (perhaps not via scanning but taking screenshot of QR code and opening it in Ledger Live. Without this we're unable to interact with Ethereum smart contracts using Ledger Nano X on iOS.

**Comment by craben20** [comment]
Yes, this is a huge user experience flaw. Ledger Live supports ERC-20 storage but doesn't offer a wc:// interface for dApps...

**Comment by hapm** [comment]
I would love to see WalletConnect implemented as well, with qr code and wc:// support.
