### ISSUE TITLE
Add biometric unlock compatible with Anrdoid 10 (Face unlock)

### ISSUE THREAD

**Issue by d-rez** [LedgerHQ/ledger-live-mobile#1105]
- [x] I have checked this feature was not yet requested.

Currently only fingerprint biometic auth is supported which makes it a pain for phones that don't have a fingerprint scanner and only have face unlock (like Pixel 4)

Since the framework already exists this should be relatively easy

#### Part of the application

Security, login, startup

**Comment by gre** [comment]
we'll take a look at this tomorrow. cc @MortalKastor

**Comment by MortalKastor** [comment]
Unfortunately the library we rely on doesn't support face unlock on Android, and, as far as I can tell, there is currently no React Native library supporting that.

Don't expect support for this feature in the short term, sorry.

**Comment by d-rez** [comment]
Oh well :(

What about https://www.npmjs.com/package/react-native-biometrics? Sorry just the first (or third) google result I found, I actually have no idea on what's being used to develop this app lol

Thanks anyway. Should this be left open for the future?

**Comment by Mythris29** [comment]
Just wanted to bump this to show support for this feature. I'm moving to the Pixel 4 XL this month and it sucks to not have biometric unlock supported for face unlock.

**Comment by d-rez** [comment]
There's kind-of a workaround, i.e. LastPass can auto-fill the app password after you face-auth with LastPass.

Not perfect but better than entering the password manually I guess

Native biometric would be best though

**Comment by JunichiSugiura** [comment]
We recently upgraded react-native-fingerprint-scanner to v4.0.0. It should enable the "Face Unlock" feature on supported devices. I haven't tested on newer android devices though.

[[updated] v4.0.0: Support Androidx Biometrics API](https://github.com/hieuvp/react-native-fingerprint-scanner/releases/tag/v4.0.0)

**Comment by Mythris29** [comment]
> We recently upgraded react-native-fingerprint-scanner to v4.0.0. It should enable the "Face Unlock" feature on supported devices. I haven't tested on newer android devices though.
> 
> [[updated] v4.0.0: Support Androidx Biometrics API](https://github.com/hieuvp/react-native-fingerprint-scanner/releases/tag/v4.0.0)

It doesn't appear to be working on the Pixel 4 XL. I'm not seeing an option for Face Unlock.

**Comment by d-rez** [comment]
@Mythris29 I believe Ledger needs to enable it in their app

@gre would you guys be able to revisit this? The bio auth option is not present in settings on a Pixel 4

Thanks!

**Comment by gre** [comment]
What @JunichiSugiura said is not yet in production. While we didn't give a try yet there is a chance it will work. We'll try to get our hand on a device that have faceid to check if it works.

**Comment by d-rez** [comment]
Looks like this got silently (accidentally) implemented?

After re-installing the app recently, I was able to set a Password Lock in the app, then flip the Fingerprint toggle and now face recognition unlocks the app :)

Looks good to me, I think this is good to close now
