### ISSUE TITLE
Is Android 7 still supported?

### ISSUE THREAD

**Issue by euh39ane29lqpx2** [LedgerHQ/ledger-live-mobile#1128]
Hi,

I have factory reseted my Samsung A3 2016 ROM: OPV Android 7;Security 1 August 2019.
Since then, ledger live is no longer working with nano s. 

Nano s is recognized by LL but it's stuck on 'open the bitcoin app on your Ledger Nano S' , when i open BTC app on Ledger there is no reaction, android however recognize connected ledger as 'keyboard' - is that right?

Second phone: Redmi 7 with Android 9 - no problems, everything works just fine.

**Comment by gre** [comment]
@euh39ane29lqpx2 thanks for your Github issue. You might want to send a message to our techsupport as well.

One question: does the Manager work or it does not access neither? The device is displayed in the list but nothing happen when you click on it?

**Comment by euh39ane29lqpx2** [comment]
Hi,

Manager sees ledger, when i click on it it gets stuck at 'navigate to dashboard on your ledger nano s'

**Comment by euh39ane29lqpx2** [comment]
Hello,

With new 2.0 version of the app everything is working again.
