### ISSUE TITLE
Counter values differ in various places in app

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-mobile#1137]
#### Ledger Live Version and Operating System

1.8.2 (arm64-v8a 67)

#### Expected behavior

Counter value matches exactly on all pages. Euros are used.

#### Actual behavior

Differences found:

"Portfolio" Total (in graph) differs from "Asset Allocation" Total.
"Accounts" Overview differs from "Account Detail", confirmed for following assets:
* BTC
* LTC
* ETH
* XTZ
* XRP

Tezos, shows THREE different counter values. In my particular case:

XTZ on accounts overview, XTZ 425 = EUR 561.07
XTZ accout detail, XTZ 425 = EUR 505.89
XTZ delegation, XTZ 425 = EUR 676.11

#### Steps to reproduce the behavior

Not sure what triggers this but I have seen app showing correct values so it seems intermittent.

**Comment by dslutej** [comment]
Dunno if I just didn't notice it before, or sporadically happening, but:

On the overview: Selecting "WEEK" or "YEAR" shows the same value as on "ASSET ALLOCATION" screen. "MONTH" shows a different value.

**Comment by dslutej** [comment]
Have not seen this in recent versions.

**Comment by gre** [comment]
This was addressed and will be deployed in a future 2.18
