### ISSUE TITLE
Incorrect AUDBTC counter value

### ISSUE THREAD

**Issue by JacqualineChamber** [LedgerHQ/ledger-live-mobile#1154]
#### Expected behaviour 

Correct BTCAUD value is retrieved

#### Actual behaviour

Incorrect BTCAUD value is retrieved

Please don’t use acx.io they are a scam exchange I’m Australia and they do not have the correct BTC value. Consider using values from independent reserve or BTC markets

**Comment by cthepot-ledger** [comment]
Duplicate of #1137 will be fixed with new countervalue system we will be introducing shortly
