### ISSUE TITLE
Ethereum Sync Error Ledger Live Version 1.8.2 iOS and Win 10.

### ISSUE THREAD

**Issue by majestik-crypto** [LedgerHQ/ledger-live-mobile#1156]
#### Ledger Live Version 1.8.2 ios and Windows 10 Ledger Live Version.

- tested on Ledger Live 1.8.2
- Phone version: iPhone XS 
 Errorcode: <NSHTTPURLResponse : 0x281cb2ca0>
{ URL: https://exploreres.api.live.edger.co...
Something went wrong. Please retry or contact us

**Comment by gre** [comment]
This was a temporary backend incident. Fixed last night.
