### ISSUE TITLE
No AUDBTC counter value returned

### ISSUE THREAD

**Issue by faheys** [LedgerHQ/ledger-live-mobile#1173]
#### Ledger Live Version and Operating System
- tested on Ledger Live **2.0.0(arm64-v8a 83)**
- Phone version: **Samsung Galaxy S10e**

#### Expected behavior
Asset value is displayed in AUD currency.

#### Actual behavior
Value is returned as "AUD 0.00". 
Other currencies seem to work fine e.g. USD

#### Steps to reproduce the behavior
Set counter value to AUD and view portfolio.

**Comment by gre** [comment]
closing in favor of https://github.com/LedgerHQ/ledger-live-mobile/issues/1154
