### ISSUE TITLE
Huge bump in Portfolio | Bitcoin graph

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-mobile#1178]
#### Ledger Live Version and Operating System

Ledger Live 2.0.1 desktop.
Windows 10.

#### Expected behavior

Correct graph.

#### Actual behavior

![image](https://user-images.githubusercontent.com/22919263/76892485-15943a00-688b-11ea-829e-213718725d6e.png)

#### Steps to reproduce the behavior

Portfolio | Bitcoin. 

Details, Bitcoin portfolio has two sep accounts. The images below are the two accounts. Notice that the dates are not quite aligned. 

![image](https://user-images.githubusercontent.com/22919263/76893262-56d91980-688c-11ea-976e-68fd9bf1b911.png)

![image](https://user-images.githubusercontent.com/22919263/76893281-5e98be00-688c-11ea-8748-a240d06565a8.png)

So when merged:

![image](https://user-images.githubusercontent.com/22919263/76893608-ef6f9980-688c-11ea-8e08-a6bcf78aaea7.png)

Which would explain the bump... But is actually wrong because the dates are not properly aligned.

**Comment by gre** [comment]
what is the rates selected in settings > rates? did you try clear cache?

**Comment by gre** [comment]
we assume this is fixed now but please tell us if it's still not (after making sure the settings/rates have a good exchange and do a clear cache.

**Comment by dslutej** [comment]
Rates from Coinbase, clear cache did not help. I'll check when I get back to my desktop computer.

**Comment by gre** [comment]
I do not reproduce on my side

from your initial screenshot i would expect the glitch to be visible on the chart inside Settings>Crypto assets>Rates, but it's fine on my side:

<img width="699" alt="Capture d’écran 2020-03-24 à 08 49 28" src="https://user-images.githubusercontent.com/211411/77400990-64226680-6dac-11ea-8528-a34e181e60b4.png">

**Comment by dslutej** [comment]
It is not an issue with rates. It is an issue with two bitcoin accounts being improperly aligned in the graph. 

I explained it very confusingly, sorry, I'll try again. 

In the first sceenshot, you see the graph over BITCOIN assets, that includes **both** accounts. 

In the second and third screenshot you see graph for each bitcoin account **separately**. In both graph 1Y range was selected. 

At a point in time I transferred coins from one account to the other (in a few steps). **All** coins were eventually transferred. (Move to a bech32 account).

**Comment by dslutej** [comment]
Also note that the graphs are showing the amount in bitcoin, not fiat equivalent.

**Comment by dslutej** [comment]
I can confirm that this is still an issue.

**Comment by gre** [comment]
This issue was addressed and a fix will be deployed in a future 2.18.0
