### ISSUE TITLE
 hello@ledger.fr -OVER 7 DAYS no ANSWER!

### ISSUE THREAD

**Issue by fundsCommunity** [LedgerHQ/ledger-live-mobile#1186]
Help I have sent ERC20 Tokens to my Wallet Address.

I have not recieved my coins and it has been over 7 days no response please indicate whether or not it is there. I set up application while transaction took place. Etherscan.io is showing that the transfer took place to this address please contact -cloud@funds.community- I would like to send to my metamask, if it isn't possible to store in this ledger account.

Thank you!

**Comment by gre** [comment]
which ERC20 tokens?

**Comment by fundsCommunity** [comment]
SYMBOL : (FEE)
TOKEN NAME : funds Community
https://etherscan.io/token/0x52590E6f7CC7D9620C7376CC926F0FA6617D2957

**Comment by gre** [comment]
i'm afraid it's currently not in our token list. please contact support so we can add it (but I guess you already did). This is a business decision and Github issues are not the place to do these.

(cc @FabriceDautriat )
