### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by fishcharlie** [LedgerHQ/ledger-live-mobile#1274]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.3.0 (121)**
- Phone version: **iPhone 11 Pro Max**

#### Expected behavior

No crashes

#### Actual behavior

This app crashes **ALL THE TIME**!! Can the owners and executive team of Ledger actually step up and fix these problems... I mean roughly 1/3 of the times I launch the app it crashes. It's insane how bad this app is in terms of crashing...

#### Steps to reproduce the behavior

Launch the app

**Comment by gre** [comment]
**We are aware of this problem and team is actively working on finding a solution.** The cause of the issue has been clearly identified and we hope to deliver a fix. _(EXC_BAD_ACCESS in lib-ledger-core bindings)_

**Comment by blockomoco** [comment]
what is the status for fixing this ?

**Comment by fishcharlie** [comment]
@blockomoco The reality is it looks like Ledger doesn't care about their app crashing. It's absolutely insane that they are so focused on releasing new features like buying crypto within the app, instead of focusing on the priorities that actually matter, having the app not crash in the first place...

This should be considered a blocker for the Ledger team. **All** focus should be diverted to fixing this crash. No releases should go out until it's fixed.

**Comment by blockomoco** [comment]
This is indeed a very annoying issue. Tried to do a transfer yesterday and the app crashed 4 times before being usable. This keeps on happening each time Im using the app. On a positive note: the app seems to be stable if it does not crash within the first seconds.

Im using iOS with an iPhone XS, so that this issue does not seem to be specific to @fishcharlie 's configuration. In other words, this is likely affecting a lot of users.

@gre hope you folks can fix this asap

**Comment by fishcharlie** [comment]
@blockomoco Agreed. I'd be curious to see the stats about how many users and sessions this is effecting. From my experience and perspective, it seems to be a **LOT**.

Just incredibly frustrating to have to deal with crashes so often and then to see the Ledger team only focusing on features like buying crypto within the application. What is even the point of that when the application is so incredibly unstable? Really hoping they get their priorities straight and get a fix out ASAP for this.

**Comment by cthepot-ledger** [comment]
Tentative fix with 2.13
