### ISSUE TITLE
Back Button and Close Button Confusing in Buy Crypto Page

### ISSUE THREAD

**Issue by fishcharlie** [LedgerHQ/ledger-live-mobile#1293]
#### General

Why is there both a back button and a close button when launching the buy crypto page? They both do the same thing. Absolutely unnecessary and confusing for the user. No idea the thought process behind this from the UX perspective. Makes no sense at all.

I'd recommend keeping the close button in the top right, since the page gets displayed as a modal. The back button in the top left is normally reserved for navigation view controllers where the page animates in from the right side.

**PLEASE** put the time and effort into making this application feel native and following the best practices for the iOS platform.

![IMG_0785](https://user-images.githubusercontent.com/860375/84223527-5faa4780-aa97-11ea-9bd8-df34a2a14e59.PNG)

#### Ledger Live Version

- Ledger Live **2.5.0 (137)**
- iPhone 11 Pro Max

#### Part of the application to improve

Buy Crypto Screen

**Comment by cthepot-ledger** [comment]
Fixed.
