### ISSUE TITLE
Location permission problem

### ISSUE THREAD

**Issue by script0rwins** [LedgerHQ/ledger-live-mobile#1476]
Hy 
i have a Huawei P30 Pro, Android 10, EMUI 10.1.0 an there are some issues with location permission.
App Ask for permission, i grant the permission and nothing happens.
Already tried restart, reinstall, etc...

Seems to be a bug in the "checkPermission" function.

Best Regards

**Comment by script0rwins** [comment]
![4a164f2e-432d-4e79-85f6-326a83f106fd](https://user-images.githubusercontent.com/65890041/100113004-295b5b80-2e70-11eb-92e2-5b925699abcf.jpeg)
![780bb1b3-0f4b-41d3-8916-322073901048](https://user-images.githubusercontent.com/65890041/100113008-29f3f200-2e70-11eb-891e-ad06dffeaee4.jpeg)
![37492d76-df96-4237-81a5-465aa538ebb5](https://user-images.githubusercontent.com/65890041/100113011-2a8c8880-2e70-11eb-9cd0-8042bb1950eb.jpeg)

**Comment by gre** [comment]
May I know why you think it is a bug in checkPermission? (just to know: is it just after looking at the code, or did you had an error related to is?)

We'll take a look into this issue. To confirm, you never "refused" the permission but always accepted? and then it gets stuck? or is just that no bluetooth device appears after this?

**Comment by script0rwins** [comment]
> May I know why you think it is a bug in checkPermission? (just to know: is it just after looking at the code, or did you had an error related to is?)
> 
> We'll take a look into this issue. To confirm, you never "refused" the permission but always accepted? and then it gets stuck? or is just that no bluetooth device appears after this?

Cause i had same troubles in my apps :)
But anyway to your question: no, i never refused the permission. And when i reinstall the app the window "Permission required" appears. I use "grant when app is in use" but then the ledger app mean: Location permission required.
BTW: This is the only app where the "grant always" is missing. Only "grant when app is in use" or "refuse" as options are available.

**Comment by jwright87** [comment]
Having same problem with OnePlus 5T Ledger Nano X

**Comment by theSociableme** [comment]
Having the Same problem Pixel 3a XL - Android Version 11 - Ledger Nano X

**Comment by DarrenTweedale** [comment]
same problem for pixel 3, android version 11, ledger nano x
whether I selected "Ask every time" or "allow only while using the app" it makes no difference.  
cannot progress beyond that screen and continue with setting up the app with my nano x.

**Comment by gre** [comment]
Hello,
thanks for all your feedbacks.

We have schedule this in our upcoming sprint. We'll status upgrade here when we have more information. Thanks

**Comment by angelflo** [comment]
same problem with one+ 6T
very disapointed by your application !

**Comment by nanspro** [comment]
same problem with samsung galaxy note 20 ultra. I am using nano x
This is a major blocker, hope it gets resolved soon.

**Comment by VonChair** [comment]
I can confirm the issue on Pixel 5 Android 11 as well. The app is missing the allow permission and only has Allow only while using the app for location permissions.

**Comment by nanspro** [comment]
@gre any idea when can we expect an update on google play store? I see that the PR is merged so hoping that it'll be soon fixed

**Comment by gre** [comment]
Fixed in 2.18.+
