### ISSUE TITLE
The price shown for the UNI ERC20 token is incorrect

### ISSUE THREAD

**Issue by edhedges** [LedgerHQ/ledger-live-mobile#1575]
#### Ledger Live Version and Operating System

- Tested on Ledger Live **2.20.0 (216)**
- Phone version: **iPhone 12 Pro - iOS 14.4**

#### Expected behavior

The price of the UNI ERC20 should reflect what etherscan shows when tapping into the `Show Contract` functionality of the token screen.

#### Actual behavior

The price shown is not correct and I'm not sure where it's sourcing the data from.

#### Steps to reproduce the behavior

To reproduce simply add the token to ledger live (I had done this upon receiving some UNI from their airdrop) and go to the dedicated token screen. You will notice the price is incorrect and you can even check by clicking through to etherscan, which has the correct market price shown. See the following screenshots that support this:
![IMG_6928](https://user-images.githubusercontent.com/825537/106826023-e3263380-663a-11eb-82a5-57c25d0815cd.jpg)
![IMG_6929](https://user-images.githubusercontent.com/825537/106826029-e4576080-663a-11eb-9ed8-edaf9cccb0f8.jpg)
![IMG_6930](https://user-images.githubusercontent.com/825537/106826031-e4eff700-663a-11eb-9d68-abdb9d2f67d0.PNG)

**Comment by edhedges** [comment]
I also experience this issue on Ledger Live Desktop v2.18.0 and did notice that there are some related issues closed on this, yet I'm still experiencing the problem. Related issues below:
- https://github.com/LedgerHQ/ledger-live-desktop/issues/3236
- https://github.com/LedgerHQ/ledger-live-desktop/issues/3307

**Comment by gre** [comment]
This was fixed in 2.21.x releases
