### ISSUE TITLE
App crash without active connection

### ISSUE THREAD

**Issue by momo258** [LedgerHQ/ledger-live-mobile#1656]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.24.0**
- Phone version: **Iphone x ios 14.0.1**

#### Expected behavior

when unable to sync because of missing active internet connection. Displaying a error message would be helpful.

#### Actual behavior

Starting the Ledger live app without a active internet connections. Results in the app crashing.

#### Steps to reproduce the behavior

1. Enable airplane mode or disable WiFi and mobile connection.
2. Launch the Ledger live mobile app.
3. App will start the synchronization process.
4. App will crash.

**Comment by chabroA** [comment]
Hello @momo258 

I was not able to reproduce your issue (tested on Ledger Live 2.25.2 with iPhone X on iOS 14.5).
I tested both scenarios, either with airplane mode enabled or with WIFI and mobile connection disabled. I did not encounter any unexpected behaviour or crash.

Do you still experience this issue as of today?

**Comment by momo258** [comment]
My mobile app has been updated already so i can't very this anymore. For now the issue does not exist on the newer versions.
