### ISSUE TITLE
App doesn't lock when switching to different apps/locking device.

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-mobile#716]
First I would like to thank you for the time you have all put into this app, the result is very nice. 😄

#### Ledger Live Version and Operating System

- tested on Ledger Live Mobile 1.1.9(9)
- Phone version: Samsung Galaxy S8+ running Android 8.0.0

#### Expected behavior
Lock the application after switching apps or after locking the device.

#### Actual behavior

If you unlock Ledger Live the app should lock again when you switch between apps.
This also occurs if you lock your phone.

#### Steps to reproduce the behavior
1,  Open Ledger Live mobile.
2.  Unlock the application.
3.  Go to your homescreen, lock the device or open a different application on your phone.
4.  Switch back to Ledger Live mobile.

**Comment by juan-cortes** [comment]
Current `develop` branch has this issue resolved, or should, feel free to test it if you can build it yourself and let us know if the bug is still present in that branch! Glad you like the work so far :D

**Comment by gre** [comment]
We'll soon open a Beta program for the apps (testflight/ play store ) to make testing easier
