### ISSUE TITLE
[android yarn start] crypto err

### ISSUE THREAD

**Issue by tpkeeper** [LedgerHQ/ledger-live-mobile#725]
**yarn start**
when android load from 8081 the pc console got:

>error: bundling failed: Error: While trying to resolve module `crypto` from file  `D:\android\ledger-live-mobile\node_modules\decimal.js\decimal.js`, the package  `D:\android\ledger-live-mobile\node_modules\crypto\package.json` was successful ly found. However, this package itself specifies a `main` module field that coul d not be resolved (`D:\android\ledger-live-mobile\node_modules\crypto\index.js`.  Indeed, none of these files exist:                                                                                                                                 * `D:\android\ledger-live-mobile\node_modules\crypto\index.js(.native\|\|.androi d.js\|.native.js\|.js\|.android.json\|.native.json\|.json\|.android.ts\|.native.ts\|.ts\| .android.tsx\|.native.tsx\|.tsx)`                                                    * `D:\android\ledger-live-mobile\node_modules\crypto\index.js\index(.native\|\|. android.js\|.native.js\|.js\|.android.json\|.native.json\|.json\|.android.ts\|.native.t s\|.ts\|.android.tsx\|.native.tsx\|.tsx)`                                                at ResolutionRequest.resolveDependency (D:\android\ledger-live-mobile\node_m odules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:61:15)              at DependencyGraph.resolveDependency (D:\android\ledger-live-mobile\node_mod ules\metro\src\node-haste\DependencyGraph.js:218:16)                                 at Object.resolve (D:\android\ledger-live-mobile\node_modules\metro\src\lib\ transformHelpers.js:141:30)                                                          at dependencies.map.result (D:\android\ledger-live-mobile\node_modules\metro \src\DeltaBundler\traverseDependencies.js:373:31)                                    at Array.map ()                                                       at resolveDependencies (D:\android\ledger-live-mobile\node_modules\metro\src \DeltaBundler\traverseDependencies.js:369:18)                                        at D:\android\ledger-live-mobile\node_modules\metro\src\DeltaBundler\travers eDependencies.js:188:33                                                              at Generator.next ()                                                  at step (D:\android\ledger-live-mobile\node_modules\metro\src\DeltaBundler\t raverseDependencies.js:298:30)                                                       at D:\android\ledger-live-mobile\node_modules\metro\src\DeltaBundler\travers eDependencies.js:309:15                                                           BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░ 88.9% (2553/27               08), failed.
--

**Comment by gre** [comment]
I wonder if it is related to trying to build from Windows.
I'm not sure what's happening here.
