### ISSUE TITLE
"Rate the app!" button not working

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-mobile#727]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.9(9)
- Phone version: Samsung Galaxy S8+ running Android 8.0.0

#### Expected behavior

The app will direct you to the playstore to rate the application.

#### Actual behavior
The app redirects to the play store, but gives the following error: "Item not found"

#### Steps to reproduce the behavior
1. Open Ledger Live Mobile
2. Go to the settings
3. Click on "About" 
4. Click on "Rate the app!"

**Comment by juan-cortes** [comment]
oh my!. Indeed, it's pointing to https://play.google.com/store/apps/details?id=com.google.android.apps.live instead of https://play.google.com/store/apps/details?id=com.ledger.live 🤦‍♂️
