### ISSUE TITLE
[feature request] Receive push notification when receiving assets

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-mobile#730]
- [x] I have checked this feature was not yet requested.

I think it would be really handy to receive push notifications when receiving some assets.
If the user would have a lock on the app non sensitive data will be shown.
I don't know if this possible atm because the app should be running all the time.

#### Part of the application

Notifications

**Comment by juan-cortes** [comment]
We have plans for a notification center, I don't know if this functionality will be there but it would make sense for something of the likes. Certainly on desktop while it's open we could do something like this, on mobile as you point out it might be more limited, but still, a notification saying "_You received yada yada"_ might be useful even if you're looking at the app.

**Comment by gre** [comment]
Thanks for the feature request.
It is unlikely this feature will be implemented as push notification for the privacy implication it would have right now. We'll close this issue for now and come back to you if we have a better solution for these problems.
