### ISSUE TITLE
[feature request] Pincode for logging in

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-mobile#733]
- [x] I have checked this feature was not yet requested.

I think it would be really handy to use a pincode for logging in.

#### Part of the application

Security

**Comment by gre** [comment]
you mean instead of the password lock? If yes pin code was discarded because we don't want to confuse user to use the same as the device pincode, this would be a big red flag from security PoV.

**Comment by Luuk2016** [comment]
Yes i mean instead of the normall password.
But yes that would be a big problem if people would use the same password.
And enabling only when using a special mode, like the Developer mode. Could that be something?

**Comment by juan-cortes** [comment]
I don't get what you mean @Luuk2016 , we have *this*. In what way is what you're proposing different?
![image](https://user-images.githubusercontent.com/4631227/52074541-67480b00-258a-11e9-84b5-603fbad8b3dc.png)

**Comment by gre** [comment]
- password is not mandatory so for dev mode, why not skipping setting one?
- we do support touch id if that helps
- going full digits is a no-go from security team to avoid chosing the same pin code
