### ISSUE TITLE
Android app does not auto lock when pin is set

### ISSUE THREAD

**Issue by Kryptoxic** [LedgerHQ/ledger-live-mobile#778]
I have a OnePlus 6 running Android 9.0 with the Ledger Live app. I enabled PIN and Fingerprint lock, however, the app stays unlocked as it is kept running in the background. In addition to that, there is no option to auto lock the app after a set amount of time like the Ledger Live app on desktop.

**Comment by juan-cortes** [comment]
The next version of the app should handle autolock more reliably than the current one, we might add a setting customize the time it takes to autolock in the future.

**Comment by gre** [comment]
Thanks for the issue @kryptoxic

Yeah the current released app does not yet have the lock feature. It is fixed in our upcoming release and will be shipped soon.

**Comment by Kryptoxic** [comment]
Sounds good. Great job to yall fine folks at Ledger!
