### ISSUE TITLE
Feedbacks on 1.2.0 Beta Test

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-mobile#824]
We will track here the problems encounter in the 1.2.0 beta. We will work on fixing them in the next releases.

If you want to communicate to us problems, DO NOT communicate here any personal information, GitHub remains public and technical so feel free to [privately contact Tech Support instead](https://support.ledger.com/).

## known issues

- [Android] Some big accounts might crash the app during synchronisation and produces wrong balance or operations history.

**Comment by Nafraz** [comment]
Can anyone  tell me,  is it the bugs that,  I am not able to use ledger live on MAC.  Please advise..  How do I connect to LIVE???

**Comment by Luuk2016** [comment]
@Nafraz If you are talking about the desktop app,
go to the following repo: https://github.com/LedgerHQ/ledger-live-desktop
This repo is for the mobile app only.

**Comment by Luuk2016** [comment]
Clearing the field for the recipeint address doesn't work using the button.
![afbeelding](https://user-images.githubusercontent.com/24903547/54722367-aa733300-4b64-11e9-9ea0-ee6e726de021.png)

**Comment by Luuk2016** [comment]
When filling in a very big number at the custom fees field the design will glitch a bit.
Maybe there should be a maximum fee.
![afbeelding](https://user-images.githubusercontent.com/24903547/54886598-fb976580-4e89-11e9-842c-77430ef086b0.png)

**Comment by gre** [comment]
Definitely need a max cap.

**Comment by gre** [comment]
this version is out. feedbacks should now go through the usual tech support. Thanks!
