### ISSUE TITLE
Windows Mobile 10 Support

### ISSUE THREAD

**Issue by kodxana** [LedgerHQ/ledger-live-mobile#87]
Helo! Its is possible to add support for Windows 10 Mobile powered devices?

**Comment by MortalKastor** [comment]
Knowing that Windows Mobile has a very low market share, Microsoft itself stopped new development for it, and our tight ressources, it's unlikely to happen, sorry.
But, as our code is open source, you're free to fork the project and port it if you want to.

**Comment by balthazar** [comment]
@kodxana Yes it's definitely possible! You can start [here](https://electronjs.org/docs/development/build-instructions-windows) and make a PR to help others! Thanks for your future contribution!
