### ISSUE TITLE
Allow to set number of precision for assets

### ISSUE THREAD

**Issue by josokinas** [LedgerHQ/ledger-live-mobile#910]
- [x] I have checked this feature was not yet requested.

Currently transaction sums are being rounded up, and sometimes it is hard to tell what is being exactly received.

For example, in this case 686.954194 XRP were received, however app shows as:

![Received XRP in the list of transactions](https://user-images.githubusercontent.com/20243687/58155455-ce89e800-7c6b-11e9-8a92-ed41db13c2b1.jpg)

![Received XRP in a transaction](https://user-images.githubusercontent.com/20243687/58155460-d21d6f00-7c6b-11e9-80a8-5b949fd9e913.jpg)

It would be good to be able to set how many precision numbers to use for each asset, e.g. I tend to use "6" for most of them.

#### Part of the application

- List of assets
- List of transactions
- Transaction info

**Comment by gre** [comment]
Can you tell us which version you are using for Ledger Live Mobile? Is it the 1.2.2 ? I think it's definitely fixed in our develop branch. but to be confirmed. cc @Arnaud97234

**Comment by josokinas** [comment]
Sure @gre, the version I'm using is version 1.2.2 (1).

**Comment by Amorn-Kingthong** [comment]
i will drive test with you

**Comment by cthepot-ledger** [comment]
Fixed in current version
