### ISSUE TITLE
can not pair with nano x

### ISSUE THREAD

**Issue by SenorSamuel** [LedgerHQ/ledger-live-mobile#914]
#### Ledger Live Version and Operating System

- tested on Ledger Live       **1.2.2 (1)**
- test with Nano X:              **Secure Element 1.2.4-1, MiscoController 2.8**
- Phone version:                  **iPhone 6.**

#### Expected behavior

Nano X pair successfully with Ledger Live(mobile) via bluetooth

#### Actual behavior

- Successful in the initial setup
- Once wiped, I just am never able to pair Nano X again, just stuck in the pair process forever

#### Steps to reproduce the behavior

- initial setup : pair successful, pair code display both on iPhone and Nano x
- wipe Nano X
- Setup and Pair : the code show neither on iPhone nor Nano X, and stuck in the screen as the following screenshot(**I am 1000% sure bluetooth is on**)

![](https://samuel-image-hosting.oss-cn-shenzhen.aliyuncs.com/SamuelChan/20190527114156.png)

I tried all kind of solutions:
- turn the bluetooth off and on, reboot
- reinstall Ledger live mobile
- install app via usb and then tried to connect again

None of them works! 
I am really sick of the bluetooth issues

**Comment by SenorSamuel** [comment]
Update:
I use another iPhone and successfully pair with Nano X. But the old one stay still

**Comment by SenorSamuel** [comment]
Update:
Does Ledger-Live(mobile) store sth in Keychain or some place?
After unpair operation on Ledger-Live(mobile), you are never able to get pair code anymore

**Comment by gre** [comment]
@SenorSamuel  Did you try to forget the Nano X in the iPhone Settings under Bluetooth? (for reference this is the current flow we're aware of https://support.ledger.com/hc/en-us/articles/360019301813-Fix-connection-issues )

**Comment by SenorSamuel** [comment]
yes, tried millions of times...😭
I guess the issues should be either Ledger Live(mobile) or Nano X unsuccessfully clean the pairing cache data.
I don't know if you guys could reproduce this issue or not

**Comment by SenorSamuel** [comment]
OMG, it works.
I misunderstood this reference yesterday...
will CLOSE this issue
