### ISSUE TITLE
public sdk for native mobile app

### ISSUE THREAD

**Issue by vtproduction** [LedgerHQ/ledger-live-mobile#916]
If I want to connect and communicate with Ledger X from my native mobile app, is it possible? Is there any sdk or instruction? Thanks a lot!

**Comment by gre** [comment]
we use React Native and have made a transport for react-native with the library react-native-ble-plx https://github.com/LedgerHQ/ledgerjs/tree/master/packages/react-native-hw-transport-ble

at the moment we don't have sdk for 100% native apps but we could in the future. please reach out to our team in Ledger Devs slack.
