### ISSUE TITLE
Litecoin transactions show up with a wrong date (1 day ahead)

### ISSUE THREAD

**Issue by d-rez** [LedgerHQ/ledger-live-mobile#919]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.2.2 (19)**
- Phone version: **Pixel 2 XL, Android 9 security patch May 2019**

#### Expected behavior

Litecoin transactions show up under the correct date on the list and show the same date in transaction details

#### Actual behavior

Date is correct in transaction details but when viewing transaction listing  the dates for LTC are one day ahead (ones received on 31st May appear as June 1st, ones received on May 30th appear as May 31st. There is no place in the world where it's June 1st at the time of writing this :)

All other currencies' transactions show under correct dates.

#### Steps to reproduce the behavior

Send LTC to an account that exists in the app. Possibly set the phone to Australian timezone. 

Screenshots of 2 transactions (details removed)
![image](https://user-images.githubusercontent.com/1719659/58691875-c83af080-837c-11e9-976e-8c90291608c4.png)
![image](https://user-images.githubusercontent.com/1719659/58691900-db4dc080-837c-11e9-9b50-a6b6aa16c0d1.png)
![image](https://user-images.githubusercontent.com/1719659/58691911-e0127480-837c-11e9-9841-4aa1c51c22b6.png)

**Comment by gre** [comment]
Good catch, we've noticed this bug in our side on Android, something to do with UTC dates support of our internal library probably. i'll report back to the team.

**Comment by gre** [comment]
why does a lot of texts are missing in these screenshots? I don't see any amounts 🤔

**Comment by d-rez** [comment]
Oh, simply because I cut them out... as I assumed they were irrelevant and trackable :)

All the fields were displayed properly except the date. Sorry for the confusion

**Comment by gre** [comment]
aha no worries. (because we used to have this bug in the past if you were on a non-English language because formatter)

For the date issue, we're aware of a problem (only affecting Android) and investigating.

**Comment by d-rez** [comment]
Hey @gre 

Just a heads up that it seems to be happening with even more cryptos now

BTC, LTC and XRP are all listed for me under "July 18 xxPM" in the summary but once I go into their details they show the correct date (July 17 xxPM)

**Comment by d-rez** [comment]
Seems fixed, closing
