### ISSUE TITLE
Transaction summary: receiver address not fully visible

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-mobile#924]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.2.2 (19)
- Phone version: Samsung Galaxy S8+ with Android 9.0

#### Expected behavior

Show the full receiver address.

#### Actual behavior

The address is not fully shown, you can't scroll so you cant see the full address.

#### Steps to reproduce the behavior

Create a new transaction.
Check the address at the transaction summary part.

#### Screenshot (masked a part of the address):
![20190607_111222](https://user-images.githubusercontent.com/24903547/59093875-38192000-8915-11e9-8fe4-a266f8dc3c39.jpg)

**Comment by cthepot-ledger** [comment]
Fixed in current version
