### ISSUE TITLE
Add "open eye, closed eye" = hidden amounts

### ISSUE THREAD

**Issue by zdeadex** [LedgerHQ/ledger-live-mobile#926]
Hello,

I would like to not open my account and everyone can see my balance.
Actually, when you enter your password or touch censor authentification, you are directly put on your portfolio.
A lot of application or exchange already have an open or closed eye right near all amount that can change all your amounts with *. (See attached picture with crypto.com and kucoin)

![Screenshot_20190611-162906_Cryptocom](https://user-images.githubusercontent.com/51711900/59282886-eb617c00-8c69-11e9-87c8-c7afaeeec929.jpg)
![Screenshot_20190611-162912_KuCoin](https://user-images.githubusercontent.com/51711900/59282887-eb617c00-8c69-11e9-90da-e13d3b9b61ab.jpg)

Portfolio and Accounts tab would be impacted by this feature.

Thanks in advance.
Best regards.
Adrien Faguet

**Comment by benos5000** [comment]
I would also like this feature

**Comment by gre** [comment]
fixed and imminent release =)

**Comment by zdeadex** [comment]
Woop woop !

Le mar. 24 nov. 2020 à 16:27, Gaëtan Renaudeau <notifications@github.com> a
écrit :
