### ISSUE TITLE
Bitcoin Bech32 support

### ISSUE THREAD

**Issue by emx0r** [LedgerHQ/ledger-live-mobile#932]
Support for Bitcoin Bech32 format address is needed. Especially now when is available in Ledger Live desktop app as an experimental function. 
Currently it is not possible to move coins on Bech32 from the mobile app. 
Also is there eta when Bech32 goes out of experimental?

**Comment by gre** [comment]
No ETA yet but we're only waiting one remaining fix to be delivered in lib-ledger-core and we should be good to deliver it as non experimental, so hopefully soon!

**Comment by emx0r** [comment]
thank you for information

**Comment by gre** [comment]
i'm closing the issue because technically fixed from dev perspective
