### ISSUE TITLE
Show balance breakdown by cryptocurrency (Asset Distribution)

### ISSUE THREAD

**Issue by 12345abcdef** [LedgerHQ/ledger-live-mobile#934]
It would be helpful if there was a way to view how much of each cryptocurrency you hold, in case you have multiple currencies loaded in or multiple accounts.

This has been implemented recently on Ledger Live Desktop so I am guessing something similar could be implemented for the mobile app.

**Comment by gre** [comment]
yes it's already fixed by https://github.com/LedgerHQ/ledger-live-mobile/pull/917
