### ISSUE TITLE
Custom counter value

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/ledger-live-mobile#946]
- [x ] I have checked this feature was not yet requested.

Please consider adding the ability for the user to add a custom counter value source api. For example, I’d like to use this api

https://api.btcmarkets.net/market/BTC/AUD/tick 

and get the last price to calculate my countervalue.

**Comment by cthepot-ledger** [comment]
We will be implementing a new counter value system that will offer more counter value but without the opportunity to select the exchange source.

**Comment by cthepot-ledger** [comment]
Duplicate of #1137
