### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/ledger-live-mobile#947]
I have checked this feature was not yet requested.

Please consider adding the ability to switch the theme of the app to dark mode.

**Comment by benos5000** [comment]
Hi, can the developers please provide some update on this?

**Comment by heigre** [comment]
> Hi, can the developers please provide some update on this?

Second that

**Comment by gre** [comment]
We have started a big refactoring effort as part of #1155 to allow to implement a dark mode in the future. There is no ETA at the moment.

**Comment by heigre** [comment]
Thanks for the update!

**Comment by sadneeds** [comment]
Hi gre, do you have any update on this?

**Comment by fishcharlie** [comment]
Ledger is obviously doing a great job at communication in regards to this issue.

This issue was created in 2019, has more up votes than any other issue, and hasn’t received an update from Ledger in almost a year.

@gre Why has there been no update on this (your most up voted issue) in almost a year?

**Comment by gre** [comment]
It's happening really really soon! Stay tuned 🙂

**Comment by fishcharlie** [comment]
https://twitter.com/ledger/status/1359547870857330690?s=21

When @gre said `It's happening really really soon` I expected maybe a week or something. Did not expect it to be 2 days later. So really pleasant surprise.

**GREAT** job to the entire team who worked on this. I really appreciate this feature!!

**Comment by gre** [comment]
FIXED
