### ISSUE TITLE
Option to disable OTG autorun needed

### ISSUE THREAD

**Issue by dzid26** [LedgerHQ/ledger-live-mobile#959]
#### Ledger Live Version

- Ledger Live 1.3.0

#### Part of the application to improve
I have really annoying problem. Whenever I connect my phone to a touchscreen that I use in my car, Ledger Live opens without asking.  Probably because touchscreen is an USB device with some no name PID/VID that matches ledger's. LedgerLive should only open activity when real Ledger is connected. Or at least there should be an option to disable the autorun in the settings.

**Comment by gre** [comment]
If you go into Android app settings, you should be able to configure that in fact, it's when you check "don't ask again" that it enabled Android's feature to open the Ledger Live app when a ledger device is plugged. I'm not sure if we can easily configure that in our side but we'll see.
The main issue is that when you switch app/dashboard on the nano devices, it's recreate a usb connection so it's going to pop-up each time you switch app on the device if not enabling that "don't ask again"' thing

**Comment by dzid26** [comment]
"Don't ask again" doesn't display anymore in this version of Ledger. But even if it did, this is useless android option as it only is remembered until device is disconnected (completely defeats its purpose). 

So no, there is no way to disable it. 

But I just checked PID/vid for my touchscreen device. The pid _almost_ matches [Ledger Nano S (00001)  ](https://github.com/LedgerHQ/ledger-live-mobile/blob/5818c16f272f7428f4b514c11935875ab07fea1c/android/app/src/main/res/xml/usb_device_filter.xml#L4)
But Vid is different: 

Device Path: /dev/bus/usb/001/003
Device Class: Use class information in the Interface Descriptors (0x0)
Vendor ID:  222a
Vendor Name (reported):  ILITEK
Vendor Name (from DB):  
Product ID:  **0001**
Product Name (reported):  ILITEK-TP
Class: Human Interaction Device (0x3)
Endpoint: #0
Address        : 0x82 (10000010)
Number         : 2
Direction      : Inbound (0x80)


So I am wondering if the filtering mechanism works. Or whether the filter could be narrowed down to only "Ledger" vendor.

**Comment by gre** [comment]
ok thanks for the detail! we probably wrongly select productId instead of vendorId! we'll investigate and come back to you shortly, thanks for the detail.

cc @juan-cortes

**Comment by juan-cortes** [comment]
Surely looks like we are matching product id from what @dzid26 is describing, however on the transport we are checking the vendor id. https://github.com/LedgerHQ/ledgerjs/blob/1f955ad133590af9dda32910ce5c59738905b102/packages/react-native-hid/src/index.js#L32  to ensure a match so I'll need to dig further tomorrow.

**Comment by juan-cortes** [comment]
@dzid26 can you provide us with the model and version of Android you are running?

**Comment by gre** [comment]
it should be fixed!
