### ISSUE TITLE
Wrong balance after sending funds from a bech32 address

### ISSUE THREAD

**Issue by lviggiano** [LedgerHQ/ledger-live-mobile#993]
#### Ledger Live Version and Operating System

Ledger Live Mobile 1.3.0 (3145749)
Android 8.1.0 OPM1.171019.019 Kernel 3.18.71-perf-gbb71efc (Xiaomi Redmi 5 plus)
To double check I used the destop app: Ledger Live 1.12.0 

#### Expected behavior

After sending 0.00208276 BTC  from a bech32 address containing 0.1 btc it is expected that the new balance on Ledger Live Mobile displays  proper amount (minus the fee); in my case it should have displayed 0.09791236 BTC. 

#### Actual behavior

I got the new balance to 0 BTC. 
It seems that the mobile app doesn't consider the change address as mine. Fortunately on the desktop application the balance is properly displayed.

#### Steps to reproduce the behavior

1. open ledger live on mobile
2. open a bech32 account with 0.1 btc
3. connect the Ledger Nano S with an OTG usb cable.
4. send 0.00208276 btc to a destination address
5. confirm the destination address on the ledger nano s.
6. check the account balance (now it displays 0 btc)

You can verify the transaction on explorer. Hash of the transaction: 
< removed >

I can send you the screenshot (mobile and desktop), if that helps.

I also waited several confirmations, still zero btc on my mobile app.

I tried to re-import the bech32 account from desktop app to the mobile app, still it displays 0 btc on the mobile app.

It seems to me, that the mobile app doesn't consider the change address as its own.

Question: when I send funds to a destination address, the ledger nano s asks for confirmation of the destination address to avoid malwares... but no confirmation is asked for the change address: a malware could forge the change address or does the ledger nano s verify that the change address is valid and not forged by some malware?

This time, it looks like the funds have not be lost. What happens if funds get lost for a bug? Does ledger refund the user or there is no liability in case of lost funds due to a bug? (just to know, I got a bit scared)

Thanks, and best regards.
Luigi.

**Comment by lviggiano** [comment]
I can send you the screenshot, if that helps.

**Comment by nscarlson** [comment]
Can confirm the same issue with native segwit addresses on the Ledger Nano X.

**Comment by dslutej** [comment]
Is this still an issue?

**Comment by lviggiano** [comment]
I stopped using the bech32 accounts, I'll leave other user's risk loosing their btc if this problem hasn't been addressed...

**Comment by gre** [comment]
here is what's exactly happening from what we know:

our explorers API does not "see" the transactions to bech32 addresses if they are too old, exactly before the time we supported bech32 on Ledger API side, therefore you don't see your entire balance, it's just a UI problem, your keys are still in your control, no risk to lose BTC it's just that Ledger Live don't "see" it all yet, until the API gets fixed.

I believe @luchenyuxx is on it.

**Comment by lviggiano** [comment]
Sounds good. Thanks for the update.

**Comment by dslutej** [comment]
I checked on desktop and compared to mobile. Same balance. Account had first transaction three weeks ago.

Slightly of topic, any way to see, list, export utxos?

**Comment by lviggiano** [comment]
This evening I'll try to re-import the bech32 account on mobile and check if the transaction shows up, then I can confirm the problem is solved.

**Comment by lviggiano** [comment]
@dslutej I don't know about the utxo, but you can export the xpub from the desktop app, right-clicking on the account and choosing 'export xpub' or something like that (I cannot check at the moment). Once you have the xpub you can check the derived addresses using key utility 'ku' ( from http://github.com/richardkiss/pycoin ) at the command line:

```
$ ku -j -s1/0-50 extendedxpub
```

From the addresses you can scan an explorer to check associated utxo.

I don't know if you can export them from the wallet.

**Comment by dslutej** [comment]
Thanks! Ku worked nice for deriving public addresses.

**Comment by lviggiano** [comment]
Hi everyone.

Today I made some tests moving BTC from a p2sh address (segwit 3) to a bc1 address, then from a bc1 address to another bc1 address in another account using the mobile app on android, an OTC cable (original Ledger cable with a cheap OTG adapter). All seems ok. Checking the transaction history on the account that previously was giving problems I can see that the bitcoin asset chart is consistent with the desktop ledger app. 

So, for my understanding, the problem looks solved.

**Comment by lviggiano** [comment]
@dslutej latest version of ledger live desktop allows to export a csv of all transactions. check it out!

**Comment by dslutej** [comment]
@lviggiano, ooh. *insert Nice Meme*
